TOKENIZER_LENGTH: 64400
START_OF_TEXT: 1
END_OF_TEXT: 7
START_OF_SPEECH: 64401  # TOKENIZER_LENGTH + 1
END_OF_SPEECH: 64402    # TOKENIZER_LENGTH + 2
START_OF_HUMAN: 64403   # TOKENIZER_LENGTH + 3
END_OF_HUMAN: 64404     # TOKENIZER_LENGTH + 4
START_OF_AI: 64405      # TOKENIZER_LENGTH + 5
END_OF_AI: 64406        # TOKENIZER_LENGTH + 6
PAD_TOKEN: 64407        # TOKENIZER_LENGTH + 7
AUDIO_TOKENS_START: 64410  # TOKENIZER_LENGTH + 10
