TOKENIZER_LENGTH: 151669
START_OF_TEXT: 151643
END_OF_TEXT: 151645
START_OF_SPEECH: 151670  # TOKENIZER_LENGTH + 1
END_OF_SPEECH: 151671    # TOKENIZER_LENGTH + 2
START_OF_HUMAN: 151672   # TOKENIZER_LENGTH + 3
END_OF_HUMAN: 151673     # TOKENIZER_LENGTH + 4
START_OF_AI: 151674      # TOKENIZER_LENGTH + 5
END_OF_AI: 151675        # TOKENIZER_LENGTH + 6
PAD_TOKEN: 151676        # TOKENIZER_LENGTH + 7
AUDIO_TOKENS_START: 151679  # TOKENIZER_LENGTH + 10
